### PR TITLE
fix: reference ostu data updated to match expected with itk5 and vtk9

### PR DESCRIPTION
**Pull request by kayarre**
vmtk tests are not very sophisticated, and there is some small difference using vtk9+itk5 versus using vtk8+itk4 that causes the otsu tests to fail.

this update updates the reference data that fixes the failing tests when using itk5+vtk9.

The reference test data was created using slicer and simple filters.

### CODE REVIEW

**Comment by lassoan** [comment]
@lantiga could you please merge this? It would be even better if you could grant me permission to merge pull requests and then we would not need to bother with such requests. Thank you!

**Comment by lantiga** [comment]
Hey @lassoan you have access now! Thanks a lot

**Comment by lassoan** [comment]
Thank you @lantiga.

**Comment by lassoan** [comment]
@kayarre This branch looks strange. Github shows 3 commits but when I check it out then TortoiseGit shows only one commit in the branch. Also, it seems that you have modified files, which would make maintenance and possibility of transferring the data to other type of repositories (e.g., github release, girder, ...) more complicated. Could you update this branch with just adding the updated test data sets with new filenames (e.g., you can add vtk9 suffix).

**Comment by kurtsansom** [comment]
Thank @lassoan  for the feedback.
It might be strange because two of the commits are rename commits  which appear to behave differently in my experience.

e.g. when you do a `git mv` and then add new files with the old name git before comitting, git assumes new files are added and old files are replaced rather than `mv` plus new files. Here I did a `git mv`, `git commit`, `git add`, `git commit`, and then realized  duplicated `vtk8` in the file names and did another `git mv`

I am happy to be enlightened about how git works here.  

I modified this per @jcfr in [vmtk #392](https://github.com/vmtk/vmtk/pull/392)

> Could you confirm that the updated test data works when building against vtk8 ?
> 
> If not, I suggest to:
> 
> * Rename current files including `_vtk8_` in the name (e.g `imagereference/test_vmtkimageotsuthresholds_vtk8_test_otsu_image_multiple_thresholds_0.mha`
> * Add new files (no need to include `_vtk9_` as ultimately vtk8 support will be removed)
> * Update test to conditional use these

What I here you saying is to rename the updated files to have vtk9 in the name? 
`vtk8` in file names for vtk8 tests, and `vtk9`  in file names for vtk9 tests?

**Comment by kayarre** [comment]
Thank you @lassoan  for the feedback.
It might be strange because two of the commits are rename commits  which appear to behave differently in my experience.

e.g. when you do a `git mv` and then add new files with the old name git before comitting, git assumes new files are added and old files are replaced rather than `mv` plus new files. Here I did a `git mv`, `git commit`, `git add`, `git commit`, and then realized  duplicated `vtk8` in the file names and did another `git mv`

I am happy to be enlightened about how git works here.  

I modified this per @jcfr in [vmtk #392](https://github.com/vmtk/vmtk/pull/392)

> Could you confirm that the updated test data works when building against vtk8 ?
> 
> If not, I suggest to:
> 
> * Rename current files including `_vtk8_` in the name (e.g `imagereference/test_vmtkimageotsuthresholds_vtk8_test_otsu_image_multiple_thresholds_0.mha`
> * Add new files (no need to include `_vtk9_` as ultimately vtk8 support will be removed)
> * Update test to conditional use these

What I here you saying is to rename the updated files to have vtk9 in the name? 
`vtk8` in file names for vtk8 tests, and `vtk9`  in file names for vtk9 tests?

**Comment by lassoan** [comment]
> I modified this per @jcfr in vmtk #392

We have two options:
- Option A: renaming files to names of current test files simpler
- Option B: never modify file contents, always just add new version of files by new names

Option A has the advantage of simpler file names. Option B has the advantage of backward compatibility and easier maintenance (and potentially porting to other file hosting solutions).

Maybe @jcfr suggested Option A in that comment because he did not know that the test data is a separate repository, shared between all VMTK versions. I would rather go with Option B due to the simpler maintenance.

**Comment by jcfr** [comment]
> Option B: never modify file contents, always just add new version of files by new names

The approach suggested by @lassoan is sensible. 

Instead of including the `vtk8` suffix ... I then suggest to:
* keep the original files
* include a suffix describing more specifically what change in the otsu (or underlying filter) implementation 

Say differently, what justify the integration of new baselines ? How different are the results when using vtk8 vs vtk9 ?


### Background

>  in that comment because he did not know that the test data is a separate repository

I considered this and noticed there where added with a git submodule associated with a specific SHA. This is why, I suggested the file rename because previous version of VMTK would be referencing a different SHA.

Then after the VTK8 support is removed the file with the `vtk8` suffix could have been removed ...

**Comment by kayarre** [comment]
> > Option B: never modify file contents, always just add new version of files by new names

 I am good with this plan.

> * keep the original files

(I will assume I can name things appropriately in the upstream tests to give some more context)

> * include a suffix describing more specifically what change in the otsu (or underlying filter) implementation

I partially understand the underlying difference for this specific case. The tests upstream essentially take the difference between the filter output and the reference image. If any pixel value is above a threshold the test fails. The difference image has pixels that wrap around the type, e.g. 0-1 = 255  for uint8, and therefore the test fails. I used the same input data and Slicer filters to generate the new reference data.

I think a better long term solution is using something like a dice coefficient? check for wrap around values? or update the test to use a difference with a floor?

**Comment by kayarre** [comment]
I reverted the original test data, and added new files with additional suffix `vtk9` and believe 
that is sufficient for now.

 
@lassoan

**Comment by kayarre** [comment]
@lassoan this seem good for now?

**Comment by lassoan** [comment]
It looks good, I'm just wondering if you created new reference data using ITK and SimpleITK then it is probably an ITK5 change and not a VTK9. Id this is the case the it would be better to reflect that in the filenames. It would be also nice if you could add all the extra information in the pull request comments to the commit comment.

Sorry for the nitpicks. I'm OK with merging the pull request as is if you feel that these requested changes are not worth the trouble. There is always room for improvements but we don't have to do everything perfectly.

**Comment by kayarre** [comment]
I wish I was a little more patient with the process at times.

The new files were generated Directly with Slicer, so I am not really sure. I thought for sure I had confirmed that I was building itk5 and vtk8, but after looking at it again it I am using itk4. So you may be right that it is a itk4 versus itk5 thing.  woof.

I will test to confirm that it is with `itk4` versus `itk5` and then rename the files to say `itk5` instead of `ivtk9` and I will also modify the test names upstream.

Do you mind sending a linking a good example of a commit message. I tend to leave commit messages short, but I guess it would make sense to be more verbose.

**Comment by lassoan** [comment]
> Do you mind sending a linking a good example of a commit message. I tend to leave commit messages short, but I guess it would make sense to be more verbose.

A short headline is good, but it is useful to include all the conclusion of the pull request discussions in the commit comment, because it is hard to look up a pull request and get full context from there.

In this case, a good commit message would be something like this:

```
Add new reference data for ITK5

VMTK tests are not very sophisticated, and there is some small difference using ITK5 versus using ITK4 that causes the Otsu tests to fail. Difference between the reference data sets ...

This commit adds reference data created using ...
```

Which tests fail exactly? There does not seem to have many changes in Otsu filtering in ITK in recent years. This one was the only one that I could quickly find that may alter the output: https://github.com/InsightSoftwareConsortium/ITK/commit/79148b662d48bd46a32967de4308c85e01d38769
If indeed this causes the test result difference then it could be nice to refer to this commit.

**Comment by kayarre** [comment]
Yep, good catch @lassoan, It does appear to be a ITK5 issue rather than a VTK issue.

The part I am not sure how to handle is how to incorporate the the ITK version into the python test since it does not use ITK python bindings?

I haven't looked into it yet but that is my first thought. I will update the file names, upstream test names, and commit messages.

Thank you immensely for the feedback.

**Comment by lassoan** [comment]
vtkvmtkOtsuMultipleThresholdsImageFilter is the Python wrapper for the ITK filter.

**Comment by kayarre** [comment]
Right but how to check for the itk version in the test?

**Comment by jcfr** [comment]
> Right but how to check for the itk version in the test?

You could update [vtkvmtkITKFilterUtilities]()  to include `itkVersion.h` and implement the following static methods:

```
  static const char* GetITKVersion() { return itk::Version::GetITKVersion(); }
  static int GetITKMajorVersion() { return itk::Version::GetITKMajorVersion(); }
  static int GetITKMinorVersion() { return itk::Version::GetITKMinorVersion(); }
  static int GetITKBuildVersion() { return itk::Version::GetITKBuildVersion(); }
  static const char* GetITKSourceVersion() { return itk::Version::GetITKSourceVersion(); }
```

Looking at the implementation of [vtkVersion.h](https://github.com/Kitware/VTK/blob/v8.2.0/Common/Core/vtkVersion.h#L37-L60) may be helpful.

Then you should be able to retrieve the ITK version doing ` vtkvmtk.vtkvmtkITKFilterUtilities.GetITKVersion()` ...



If needed in `vtkvmtkITK` library, you could also add a class called `vtkITKUtility` to [vtkITKUtility.h](https://github.com/vmtk/vmtk/blob/master/vtkVmtk/Utilities/vtkvmtkITK/vtkITKUtility.h) and add similar static methods there ....

**Comment by kayarre** [comment]
these are the tests that fail. [test_vmtkimageotsuthresholds.py](https://github.com/vmtk/vmtk/blob/master/tests/test_vmtkScripts/test_vmtkimageotsuthresholds.py)

**Comment by kayarre** [comment]
> You could update vtkvmtkITKFilterUtilities to include `itkVersion.h` and implement the following static methods:

> If needed in `vtkvmtkITK` library, you could also add a class called `vtkITKUtility` to [vtkITKUtility.h](https://github.com/vmtk/vmtk/blob/master/vtkVmtk/Utilities/vtkvmtkITK/vtkITKUtility.h) and add similar static methods there ....



@jcfr does it make sense to pick one or the other

**Comment by kayarre** [comment]
Any specific reason to NOT put it in its own file `vtkvmtkITKVersion.h`

**Comment by kayarre** [comment]
@lassoan Is this sufficient for adding the data?

[vmtk 392](https://github.com/vmtk/vmtk/pull/392) includes the updates to access the ITK version within vmtk.

**Comment by jcfr** [comment]
Looks good to me. Thanks again for taking the time to update the pull request :pray: 

I  will let @lassoan integrate


(when squash merging `casuing` -> `causing`)

**Comment by kayarre** [comment]
Thank you immensely for the feedback @jcfr

**Pull request merged**
