### PR TITLE
chore: add new reference data for vtk 9.1.0

### PR DESCRIPTION
**Pull request by kayarre**
Updating vmtk to use vtk 9.1.0 revealed differences with the tests for `vmtksurfacebooleanOperation`
these new files cover the intersection and difference test using `vtk 9.1.0`

### CODE REVIEW

**Comment by lassoan** [comment]
Does vtk9_1 refer to VTK 9.1 or to first revision of the file for VTK9?

Does the new reference data better, similar, or worse than the previous version?

**Comment by kayarre** [comment]
> Does vtk9_1 refer to VTK 9.1 or to first revision of the file for VTK9?

yes, open to suggestions to make that clearer. sinse the difference was introduced in a minor release.

> Does the new reference data better, similar, or worse than the previous version?

The Union operator appears to give the same result as before. Both intersection and difference operators give non-trivially(?) different results. 

I added new tests that use the same criteria as the old test but with new reference data and pass as before

I also added a test that compares with the old reference data but uses a lower comparison tolerance (1e-1) for the difference and subsequently the tests pass as shown below. Some point differs on the order 0.01 between the old reference data and vtk 9.1.0 output for the intersection and difference tests, versus less than 1.0E-6 difference in vtk 9.0.3 or earlier.

```sh
test_vmtkScripts/test_vmtksurfacebooleanoperation.py::test_operations_default_tolerance[intersection-0.1-1] Reading VTK XML surface file.
Computing distance.
Distance Range: (0.0, 0.011697411685065214)
PASSED
test_vmtkScripts/test_vmtksurfacebooleanoperation.py::test_operations_default_tolerance[difference-0.1-2] Reading VTK XML surface file.
Computing distance.
Distance Range: (0.0, 0.01175887567281538)
PASSED

```

NOTES:

- I used the latest release candidate of paraview and this boolean filter [boolean filter](https://discourse.paraview.org/t/boolean-operations/1498/3) to generate the new reference data.
- The test criteria is evaluated on the maximum of the range of the distance results, rather than some average difference over the whole domain

**Comment by lassoan** [comment]
> > Does vtk9_1 refer to VTK 9.1 or to first revision of the file for VTK9?
> 
> yes, open to suggestions to make that clearer. sinse the difference was introduced in a minor release.

I would say vtk910 would be more readable, but when VTK10 will be released then version number like vtk1001 will not be very readable. So, something like these would be more clear: vtk_9_1, vtk_9-1, vtk-9_1, vtk-9-1, ...

The added tests sound great and the additional information in your comment above is very useful, so it would be great if you could add most of it to the commit comment.

**Comment by kayarre** [comment]
@lassoan thank you for the feedback. It was very helpful. I think this is what you are looking for in terms of naming and commit message?

**Comment by kayarre** [comment]
@lassoan  any thoughts on this?

**Comment by lassoan** [comment]
Done. Sorry for the delay.

**Pull request merged**
